/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    output reg spi_miso,
    output reg [3:0] spi_channel,
    output reg avr_rx,
    output reg [2:0] out,
    input sum,
    input carry,
    output reg [23:0] io_led,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  localparam ID_testState = 4'd0;
  localparam A_testState = 4'd1;
  localparam B_testState = 4'd2;
  localparam C_testState = 4'd3;
  localparam AB_testState = 4'd4;
  localparam AC_testState = 4'd5;
  localparam BC_testState = 4'd6;
  localparam ABC_testState = 4'd7;
  localparam O_testState = 4'd8;
  localparam FAIL_testState = 4'd9;
  
  reg [3:0] M_testState_d, M_testState_q = ID_testState;
  reg [26:0] M_counter_d, M_counter_q = 1'h0;
  
  always @* begin
    M_testState_d = M_testState_q;
    M_counter_d = M_counter_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    out[0+2-:3] = io_dip[16+0+2-:3];
    io_led[8+0+0-:1] = sum;
    io_led[8+1+0-:1] = carry;
    if (io_dip[16+0+0-:1] ^ io_dip[16+1+0-:1] ^ io_dip[16+2+0-:1] == sum) begin
      io_led[8+7+0-:1] = 1'h1;
    end
    if ((io_dip[16+0+0-:1] & io_dip[16+1+0-:1]) | ((io_dip[16+0+0-:1] ^ io_dip[16+1+0-:1]) & io_dip[16+2+0-:1]) == carry) begin
      io_led[8+6+0-:1] = 1'h1;
    end
    if (M_counter_q[0+24-:25] == 1'h0) begin
      
      case (M_testState_q)
        O_testState: begin
          if (carry == 1'h0 & sum == 1'h0) begin
            M_testState_d = ID_testState;
          end else begin
            M_testState_d = FAIL_testState;
          end
        end
        ABC_testState: begin
          if (carry == 1'h1 & sum == 1'h1) begin
            M_testState_d = O_testState;
          end else begin
            M_testState_d = FAIL_testState;
          end
        end
        AC_testState: begin
          if (carry == 1'h1 & sum == 1'h0) begin
            M_testState_d = ABC_testState;
          end else begin
            M_testState_d = FAIL_testState;
          end
        end
        BC_testState: begin
          if (carry == 1'h1 & sum == 1'h0) begin
            M_testState_d = AC_testState;
          end else begin
            M_testState_d = FAIL_testState;
          end
        end
        AB_testState: begin
          if (carry == 1'h1 & sum == 1'h0) begin
            M_testState_d = BC_testState;
          end else begin
            M_testState_d = FAIL_testState;
          end
        end
        C_testState: begin
          if (carry == 1'h0 & sum == 1'h1) begin
            M_testState_d = AB_testState;
          end else begin
            M_testState_d = FAIL_testState;
          end
        end
        B_testState: begin
          if (carry == 1'h0 & sum == 1'h1) begin
            M_testState_d = C_testState;
          end else begin
            M_testState_d = FAIL_testState;
          end
        end
        A_testState: begin
          if (carry == 1'h0 & sum == 1'h1) begin
            M_testState_d = B_testState;
          end else begin
            M_testState_d = FAIL_testState;
          end
        end
        ID_testState: begin
          if (io_button[1+0-:1] == 1'h1) begin
            M_testState_d = A_testState;
          end
        end
        FAIL_testState: begin
          if (M_counter_q == 1'h0) begin
            M_testState_d = ID_testState;
          end
        end
      endcase
    end
    M_counter_d = M_counter_q + 1'h1;
    
    case (M_testState_q)
      O_testState: begin
        out[0+2-:3] = 1'h0;
        io_led[0+0+0-:1] = 1'h1;
      end
      ABC_testState: begin
        out[0+2-:3] = 7'h6f;
        io_led[0+1+0-:1] = 1'h1;
      end
      AC_testState: begin
        out[0+2-:3] = 7'h65;
        io_led[0+2+0-:1] = 1'h1;
      end
      BC_testState: begin
        out[0+2-:3] = 7'h6e;
        io_led[0+3+0-:1] = 1'h1;
      end
      AB_testState: begin
        out[0+2-:3] = 4'hb;
        io_led[0+4+0-:1] = 1'h1;
      end
      C_testState: begin
        out[0+2-:3] = 7'h64;
        io_led[0+5+0-:1] = 1'h1;
      end
      B_testState: begin
        out[0+2-:3] = 4'ha;
        io_led[0+6+0-:1] = 1'h1;
      end
      A_testState: begin
        out[0+2-:3] = 1'h1;
        io_led[0+7+0-:1] = 1'h1;
      end
      ID_testState: begin
        io_led[8+3+0-:1] = 1'h1;
      end
      FAIL_testState: begin
        if (M_counter_q[22+0-:1] == 1'h1) begin
          io_led[8+3+0-:1] = 1'h1;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    M_counter_q <= M_counter_d;
    
    if (rst == 1'b1) begin
      M_testState_q <= 1'h0;
    end else begin
      M_testState_q <= M_testState_d;
    end
  end
  
endmodule
